config/routes.rb
Rails.application.routes.draw do
  root :to => 'application#index'

  get 'logout' => 'sessions#destroy', :as => 'log_out'

  get 'login' => 'sessions#new', :as => 'log_in'
  post 'login' => 'sessions#create'

  get 'register' => 'users#new', :as => 'sign_up'
  post 'register' => 'users#create'

  get 'user_id' => 'application#user_id'
  get 'current_person' => 'application#current_person', :defaults => {format: :json}

  resources :users, :except => :new
  resources :sessions, :except => :new
  resources :issues

  get 'api' => 'api#index'

  scope :api, :defaults => {format: :json} do
    resources :organizations
    resources :forums do
      scope :module => :forum do
        resources :persons do
          resources :likes
          delete 'likes' => 'likes#destroy'

          get 'subscribed_events' => 'persons#subscribed_events'
        end
        resources :events do
          resources :likes
          delete 'likes' => 'likes#destroy'

          post 'subscribes' => 'events#person_subscribe'
          get 'subscribes' => 'events#subscribes'
          delete 'subscribes' => 'events#person_unsubscribe'
        end
        resources :news do
          resources :likes
          delete 'likes' => 'likes#destroy'
        end
        resources :rooms do
          resources :likes
          delete 'likes' => 'likes#destroy'
        end
        resources :telegram_users
      end
    end
    resources :events
    resources :event_types
    resources :persons
    resources :rooms
    resources :colors
    resources :news
    resources :tasks
    resources :likes

    post 'login' => 'sessions#api_create'
    get 'current_user_id' => 'sessions#current_user_id'
    post 'logout' => 'sessions#api_destroy'
    post 'anonym_register' => 'users#api_anonym_create'
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  constraints lambda {|request| AuthConstraint.admin?(request) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount RailsAdmin::Engine => '/adminpanel', :as => 'rails_admin'

  get 'qr' => 'qr#index'
  get 'support' => 'issues#new'

  get 'manager' => 'manager#index'

  post '158767104:AAGP2dDFWEB6dnIlAuFRJJhIvSaQEsBnTsw' => 'telegram_users#command_execute'
  post '/' => 'telegram_users#root_post'

  get '/manager/*path' => 'manager#index'

  get '/:alias', to: 'forums#show'
  get '/:forum_alias/:room_alias', to: 'rooms#show'
  get '/:forum_alias/:room_alias/:event_alias', to: 'events#show'
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create, :message => "can't be blank"
  validates_uniqueness_of :email, :message => 'already in use', :allow_blank => true

  before_create :encrypt_password

  def organization=(value)

  end
  def organization

  end
  # Password and auth stuff.
  def saved_password
    @saved_password ||= BCrypt::Password.new(encrypted_password)
  end

  def saved_password=(new_password)
    @saved_password = BCrypt::Password.create(new_password)
    self.encrypted_password = @saved_password
  end

  def encrypt_password
    self.saved_password = password if password.present?
  end

  def self.authenticate email, password
    user = where(:email => email.downcase).first
    if user && user.saved_password == password
      user
    else
      nil
    end
  end
end

app/controllers/users_controller.rb
class UsersController < InheritsController
  skip_before_action :is_auth, only: [:new, :create, :api_anonym_create]

  def new
    @user = User.new
  end

  def create
    unless user_params[:email]
      flash.alert = 'Email не задан'
      render 'new'
      return
    end

    user_params[:email].downcase!

    existing_user = User.find_by_email user_params[:email]
    if existing_user
      flash.alert = 'Пользователь с таким email уже существует'
      render 'new'
      return
    end

    if user_params[:password] != user_params[:password_confirmation]
      flash.alert = 'Пароли не совпадают'
      render 'new'
      return
    end

    @user = Person.new(email: user_params[:email], password: user_params[:password])
    if @user.save!
      organization = Organization.new(name: user_params[:organization])
      @user.creator_organizations << organization
      @user.organizations << organization

      session[:user_id] = @user.id
      redirect_to manager_path, :notice => 'Добро пожаловать!'
    else
      flash.alert = 'Произошла ошибка сервера, вы не зарегистрированы :('
      render 'new'
    end
  end

  def api_anonym_create
    temp_password = KeePass::Password.generate('h{10}')

    @user = Person.new(anonym: true, password: temp_password)
    begin
      if @user.save!
        @user.email = @user.id.to_s + '@eva-events.ru'
        @user.name = '%09o' % @user.id
        @user.save

        session[:user_id] = @user.id

        respond_with(@user, :status => 200)
      else
        respond_with(@user = user, :status => 400)
      end
    rescue ActiveRecord::RecordInvalid => invalid
      puts invalid.record.errors
      Rails.logger.debug invalid.record.errors
    end
  end
  private

    def user_params
      params.require(:user).permit(:email, :organization, :password, :password_confirmation, :salt, :encrypted_password)
      #params.require(:user).permit(:email, :password_hash, :password_salt)
    end

end

app/views/users/_new.html.slim
h1 Зарегистрировать организацию
= form_for :user, url: register_path do |f|
  - if @user && @user.errors.any?
    .error_messages
      h2
        | Ошибка заполнения формы
      ul
        - for message in @user.errors.full_messages
          li
            = message
  - if flash[:alert]
    .alert.alert-warning.alert-dismissible.fade.in role="alert"
      button.close.pull-right type="button" data-dismiss="alert" aria-label="Close"
        span aria-hidden="true"
          | ×
      h4
        | Ошибка регистрации
      p
        = flash[:alert]
  .form-group.col-md-12
    .col-md-4.col-lg-3.text-right
      b Email
    .col-md-6.col-lg-7
      = f.email_field :email, :class => 'form-control', :required => true

  .form-group.col-md-12
    .col-md-4.col-lg-3.text-right
      b Название организации
    .col-md-6.col-lg-7
      = f.text_field :organization, :class => 'form-control', :required => true

  .form-group.col-md-12
    .col-md-4.col-lg-3.text-right
      b Пароль
    .col-md-6.col-lg-7
      = f.password_field :password, :class => 'form-control', :required => true

  .form-group.col-md-12
    .col-md-4.col-lg-3.text-right
      b Подтверждение пароля
    .col-md-6.col-lg-7
      = f.password_field :password_confirmation, :class => 'form-control', :required => true


  .form-group.col-md-12
    .col-md-6.col-lg-7.col-md-offset-4.col-md-offset-3
      = f.submit 'Зарегистрироваться', :class => 'btn btn-primary'

app/views/users/new.html.slim
div.container style="padding-top: 80px"
  - if current_user
    h1
      | Вы вошли в систему под email:
      = current_user.email
  -else
    = render 'new'