config/routes.rb
Rails.application.routes.draw do
  root :to => 'application#index'

  get 'logout' => 'sessions#destroy', :as => 'log_out'

  get 'login' => 'sessions#new', :as => 'log_in'
  post 'login' => 'sessions#create'

  get 'register' => 'users#new', :as => 'sign_up'
  post 'register' => 'users#create'

  get 'user_id' => 'application#user_id'
  get 'current_person' => 'application#current_person', :defaults => {format: :json}

  resources :users, :except => :new
  resources :sessions, :except => :new
  resources :issues

  get 'api' => 'api#index'

  scope :api, :defaults => {format: :json} do
    resources :organizations
    resources :forums do
      scope :module => :forum do
        resources :persons do
          resources :likes
          delete 'likes' => 'likes#destroy'

          get 'subscribed_events' => 'persons#subscribed_events'
        end
        resources :events do
          resources :likes
          delete 'likes' => 'likes#destroy'

          post 'subscribes' => 'events#person_subscribe'
          get 'subscribes' => 'events#subscribes'
          delete 'subscribes' => 'events#person_unsubscribe'
        end
        resources :news do
          resources :likes
          delete 'likes' => 'likes#destroy'
        end
        resources :rooms do
          resources :likes
          delete 'likes' => 'likes#destroy'
        end
        resources :telegram_users
      end
    end
    resources :events
    resources :event_types
    resources :persons
    resources :rooms
    resources :colors
    resources :news
    resources :tasks
    resources :likes

    post 'login' => 'sessions#api_create'
    get 'current_user_id' => 'sessions#current_user_id'
    post 'logout' => 'sessions#api_destroy'
    post 'anonym_register' => 'users#api_anonym_create'
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  constraints lambda {|request| AuthConstraint.admin?(request) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount RailsAdmin::Engine => '/adminpanel', :as => 'rails_admin'

  get 'qr' => 'qr#index'
  get 'support' => 'issues#new'

  get 'manager' => 'manager#index'

  post '158767104:AAGP2dDFWEB6dnIlAuFRJJhIvSaQEsBnTsw' => 'telegram_users#command_execute'
  post '/' => 'telegram_users#root_post'

  get '/manager/*path' => 'manager#index'

  get '/:alias', to: 'forums#show'
  get '/:forum_alias/:room_alias', to: 'rooms#show'
  get '/:forum_alias/:room_alias/:event_alias', to: 'events#show'
end

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    title EvaEvents #{yield(:title)}
    base href="/"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = analytics_init if Rails.env.production?
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tag
  body
    nav.navbar.navbar-default style=("position:fixed; z-index:100;width: 100%;")
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed data-target="#bs-example-navbar-collapse-2" data-toggle="collapse" type="button"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="/"
            =image_tag "eva.png"
        .collapse.navbar-collapse
          ul.nav.navbar-nav
            -if current_user
              li
                a href="/manager"
                  =' fa_icon 'tasks'
                  | Управлениe
              li
                a href="#" class="disabled"
                  =' fa_icon 'info'
                  | О компании
              li
                a href="#" class="disabled"
                  =' fa_icon 'line-chart'
                  | Управленческий учет
              li
                =link_to rails_admin_path, target: "_blank" do
                  =' fa_icon 'database'
                  | База данных
              li
                a href="#" class="disabled"
                  =' fa_icon 'skyatlas'
                  | Файлы
              li
                a href="#" class="disabled"
                  =' fa_icon 'cogs'
                  | Настройки
            -else
              li.first.dropdown
                a href="/" title="Главная"
                  | Главная
            /li.last.dropdown
            /  a.dropdown-toggle aria-expanded="false" data-toggle="dropdown" href="#" role="button"
            /    | Связаться с нами
            /    span.caret
            /  ul.dropdown-menu
            /    li.first
            /      a href="http://rize.su/l/connect/gruppa-v-vk" title=("Группа в ВК")  Группа в ВК
            /    li.last
            /      a href="http://rize.su/l/connect/contacts" title="Контакты"  Контакты
          ul.nav.navbar-nav.navbar-right
            -if current_user
              /li
              /  =link_to "Личный кабинет #{current_user.email}", cabinet_path
              li
                =link_to 'Выйти', log_out_path
            -else
              li
                =link_to 'Зарегистрироваться', sign_up_path
              li
                =link_to 'Войти', log_in_path
    /ng-strict-di=''
    = yield

app/views/layouts/blank.html.slim
<!DOCTYPE html>
html
  head
    title EvaEvents
    base href="/"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = analytics_init if Rails.env.production?
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tag
  body
    div.container
      = yield